# .github/workflows/bot-alert.yml

name: Kamino Yield Alert Bot

# This is the "WHEN to run" section
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # TEST: Runs at 04:00 UTC (12:00 PM MYT)
    - cron: '0 4 * * *'

# --- THIS PART IS ESSENTIAL ---
# This is the "WHAT to do" section
jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alert bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
