name: Kamino Yield Alert Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # 9:00 AM MYT (01:00 UTC)
    - cron: '0 14 * * *' # 10:00 PM MYT (14:00 UTC)

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install python-dotenv
        run: pip install python-dotenv

      - name: Run alert bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
