# .github/workflows/kamino_bot.yml

name: Kamino Yield Alert Bot

# NEW "on" SECTION
on:
  # This lets you still run it with a push
  push:
    branches:
      - main
  # This lets you still run it manually
  workflow_dispatch:
  # THIS IS THE NEW TRIGGER FOR THE EXTERNAL CRON JOB
  repository_dispatch:
    types: [daily-alert] # We will use this event name later
    
jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alert bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
