name: Kamino Yield Alert Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '35 14 * * *'  # TEMP: Set this to 2–3 minutes from now UTC time

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install python-dotenv
        run: pip install python-dotenv

      - name: Run alert bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
